AWSTemplateFormatVersion: '2010-09-09'
Description: LambdaUniverse Stack for gobal Lambda@Edge functions
Resources:
  LambdaAtEdgeExecutionRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
          -
            Effect: "Allow"
            Principal:
              Service:
                - "edgelambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/service-role/lambda/"
  LambdaRolePolicies:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "allow-cloudwatch-logs-in-all-regions"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action: [
              "logs:CreateLogGroup",
              "logs:CreateLogStream",
              "logs:PutLogEvents"
            ]
            Resource: "arn:aws:logs:*:*:*"
      Roles:
        -
          Ref: "LambdaAtEdgeExecutionRole"

  lambdaViewerRequestLocalS3BucketRedirector:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: viewer_request_local_s3_bucket_redirector
      Description: "A Lambda@Edge function to http 302 redirect requests to a region specific bucket, instead of serving the files via CloudFront"
      Handler: "viewer_request_local_s3_bucket_redirector.handler"
      Role:
        Fn::GetAtt:
          - "LambdaAtEdgeExecutionRole"
          - "Arn"
      Code:
        ZipFile: |
          console.log(\"Empty function, please upload a zip via the webinterface\")
      Runtime: "nodejs6.10"
      Timeout: "1"
      MemorySize: "128"
  lambdaViewerRequestUniverseVersionedJson:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: viewer_request_universe_versioned_json
      Description: ""
      Handler: "viewer_request_universe_versioned_json.handler"
      Role:
        Fn::GetAtt:
          - "LambdaAtEdgeExecutionRole"
          - "Arn"
      Code:
        ZipFile: |
          console.log(\"Empty function, please upload a zip via the webinterface\")
      Runtime: "nodejs6.10"
      Timeout: "1"
      MemorySize: "128"

  CloudWatchLambdaUniverseDashboard:
    Type: "AWS::CloudWatch::Dashboard"
    Properties:
      DashboardName: LambdaUniverse
      DashboardBody: |
        {
            "widgets": [
                {
                    "type": "metric",
                    "x": 0,
                    "y": 0,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "viewer_request_local_s3_bucket_redirector", "not-redirecting" ],
                            [ "viewer_request_local_s3_bucket_redirector", "no-redirect-target" ],
                            [ "viewer_request_local_s3_bucket_redirector", "redirects" ]
                        ],
                        "region": "us-east-1",
                        "title": "us-east-1"
                    }
                },
                {
                    "type": "metric",
                    "x": 6,
                    "y": 0,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "viewer_request_local_s3_bucket_redirector", "not-redirecting" ],
                            [ "viewer_request_local_s3_bucket_redirector", "no-redirect-target" ],
                            [ "viewer_request_local_s3_bucket_redirector", "redirects" ]
                        ],
                        "region": "us-east-2",
                        "title": "us-east-2"
                    }
                },
                {
                    "type": "metric",
                    "x": 12,
                    "y": 0,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "viewer_request_local_s3_bucket_redirector", "not-redirecting" ],
                            [ "viewer_request_local_s3_bucket_redirector", "no-redirect-target" ],
                            [ "viewer_request_local_s3_bucket_redirector", "redirects" ]
                        ],
                        "region": "us-west-1",
                        "title": "us-west-1"
                    }
                },
                {
                    "type": "metric",
                    "x": 18,
                    "y": 0,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "viewer_request_local_s3_bucket_redirector", "not-redirecting" ],
                            [ "viewer_request_local_s3_bucket_redirector", "no-redirect-target" ],
                            [ "viewer_request_local_s3_bucket_redirector", "redirects" ]
                        ],
                        "region": "us-west-2",
                        "title": "us-west-2"
                    }
                },
                {
                    "type": "metric",
                    "x": 0,
                    "y": 6,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "viewer_request_local_s3_bucket_redirector", "not-redirecting" ],
                            [ "viewer_request_local_s3_bucket_redirector", "no-redirect-target" ],
                            [ "viewer_request_local_s3_bucket_redirector", "redirects" ]
                        ],
                        "region": "ap-south-1",
                        "title": "ap-south-1"
                    }
                },
                {
                    "type": "metric",
                    "x": 6,
                    "y": 6,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "viewer_request_local_s3_bucket_redirector", "not-redirecting" ],
                            [ "viewer_request_local_s3_bucket_redirector", "no-redirect-target" ],
                            [ "viewer_request_local_s3_bucket_redirector", "redirects" ]
                        ],
                        "region": "ap-northeast-2",
                        "title": "ap-northeast-2"
                    }
                },
                {
                    "type": "metric",
                    "x": 12,
                    "y": 6,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "viewer_request_local_s3_bucket_redirector", "not-redirecting" ],
                            [ "viewer_request_local_s3_bucket_redirector", "no-redirect-target" ],
                            [ "viewer_request_local_s3_bucket_redirector", "redirects" ]
                        ],
                        "region": "ap-southeast-1",
                        "title": "ap-southeast-1"
                    }
                },
                {
                    "type": "metric",
                    "x": 18,
                    "y": 6,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "viewer_request_local_s3_bucket_redirector", "not-redirecting" ],
                            [ "viewer_request_local_s3_bucket_redirector", "no-redirect-target" ],
                            [ "viewer_request_local_s3_bucket_redirector", "redirects" ]
                        ],
                        "region": "ap-southeast-2",
                        "title": "ap-southeast-2"
                    }
                },
                {
                    "type": "metric",
                    "x": 0,
                    "y": 12,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "viewer_request_local_s3_bucket_redirector", "not-redirecting" ],
                            [ "viewer_request_local_s3_bucket_redirector", "no-redirect-target" ],
                            [ "viewer_request_local_s3_bucket_redirector", "redirects" ]
                        ],
                        "region": "ap-northeast-1",
                        "title": "ap-northeast-1"
                    }
                },
                {
                    "type": "metric",
                    "x": 6,
                    "y": 12,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "viewer_request_local_s3_bucket_redirector", "not-redirecting" ],
                            [ "viewer_request_local_s3_bucket_redirector", "no-redirect-target" ],
                            [ "viewer_request_local_s3_bucket_redirector", "redirects" ]
                        ],
                        "region": "ca-central-1",
                        "title": "ca-central-1"
                    }
                },
                {
                    "type": "metric",
                    "x": 12,
                    "y": 12,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "viewer_request_local_s3_bucket_redirector", "not-redirecting" ],
                            [ "viewer_request_local_s3_bucket_redirector", "no-redirect-target" ],
                            [ "viewer_request_local_s3_bucket_redirector", "redirects" ]
                        ],
                        "region": "eu-central-1",
                        "title": "eu-central-1"
                    }
                },
                {
                    "type": "metric",
                    "x": 18,
                    "y": 12,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "viewer_request_local_s3_bucket_redirector", "not-redirecting" ],
                            [ "viewer_request_local_s3_bucket_redirector", "no-redirect-target" ],
                            [ "viewer_request_local_s3_bucket_redirector", "redirects" ]
                        ],
                        "region": "eu-west-1",
                        "title": "eu-west-1"
                    }
                },
                {
                    "type": "metric",
                    "x": 0,
                    "y": 18,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "viewer_request_local_s3_bucket_redirector", "not-redirecting" ],
                            [ "viewer_request_local_s3_bucket_redirector", "no-redirect-target" ],
                            [ "viewer_request_local_s3_bucket_redirector", "redirects" ]
                        ],
                        "region": "eu-west-2",
                        "title": "eu-west-2"
                    }
                },
                {
                    "type": "metric",
                    "x": 6,
                    "y": 18,
                    "width": 6,
                    "height": 6,
                    "properties": {
                        "view": "timeSeries",
                        "stacked": false,
                        "metrics": [
                            [ "viewer_request_local_s3_bucket_redirector", "not-redirecting" ],
                            [ "viewer_request_local_s3_bucket_redirector", "no-redirect-target" ],
                            [ "viewer_request_local_s3_bucket_redirector", "redirects" ]
                        ],
                        "region": "sa-east-1",
                        "title": "sa-east-1"
                    }
                }
            ]
        }

